[project]
name = "jurasofish-github-io"
version = "0.1.0"
description = "hey"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pelican[markdown]",
    "pelican-render-math",
    "beautifulsoup4",
    "python-gettext",
]
