name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Build static files
        run: make static

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pelican_project/output/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
